server:
    port: 8080
    servlet:
        context-path: /
spring:
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
        serialization:
            FAIL_ON_EMPTY_BEANS: false
    datasource:
        url: jdbc:mysql:///test2?seUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
        username: root
        password: admin123
        driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
    mapper-locations: classpath:/mapping/*.xml
    config-location: classpath:mybatis-config.xml
    type-aliases-package: classpath:com.hand.al.springbootdemo1.vo
mapper:
    identity: MYSQL
    mappers: com.hand.al.springbootdemo1.baseMapper.BaseMapper
